name: QMK Build
on:
  push:
    branches: [main]
    paths:
      - "keyboards/**"
      - "qmk.json"
      - ".github/workflows/build.yml"
  pull_request:
    branches: [main]

jobs:
  build:
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@main
    with:
      qmk_repo: qmk/qmk_firmware
      qmk_ref: master
